version: '3'

services:
  traefik:
    image: traefik:v2.2
    restart: always
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
      - "2081:8080"
    volumes:
#      - /root/traefik.sample.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: traefik
    labels:
      - "traefik.http.routers.api.rule=Host(`indexown.com`)"
      - "traefik.http.routers.api.service=api@internal"
      
