version: "2.1"
services:
  baiduNetdisk:
    image: johngong/baidunetdisk:latest
    container_name: baiduNetdisk
    environment:
      - TZ=Asia/Shanghai
      - VNC_PASSWORD=
    volumes:
      - baiduyun_config:/config 
      - /bddownload:/config/baidunetdiskdownload
    
    ports:
      - 5900:5900 
      - 6080:5800 
    restart: unless-stopped
volumes:
   baiduyun_config: